version: "3.9"

services:
  app:
    build: .
    container_name: gpt_app
    # volumes:
    #   - .:/app
    # command: ["go", "run", "cmd/server/main.go"]
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    networks:
      - gpt_network
    depends_on:
      mysql:
        condition: service_healthy
  
  mysql:
    image: mysql:8.0
    container_name: gpt_mysql
    restart: always
    env_file:
      - .env
    ports:
      - "33064:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --innodb-buffer-pool-size=512M
      - --max-connections=300
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gpt_network

volumes:
  mysql_data:

networks:
  gpt_network:
    driver: bridge
